### ISSUE TITLE
Context is now available via the Request object (go1.7)

### ISSUE THREAD

**Issue by amoghe** [dghubble/ctxh#1]
You may already know this, but since the README says something about deprecating this I'm wondering if now is the right time to do so (I can help with parts of gologin that may need to change).

Although this will force users to upgrade go 1.7 if they haven't already done so.

**Comment by dghubble** [comment]
With 1.7, the context package is available as "context". The import path will be updated once 1.7 can be widely assumed (its the default in most distros, closer to 1.8). Well after that, the ContextHandler will be evaluated again, but no plans to change signatures any time soon, that interface still works well.

**Comment by dghubble** [comment]
Go 1.8 is out, gologin was migrated to the new context in v2.0.0, and this package has been marked DEPRECATED.
